pic_upload/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('picuploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

picuploader/urls.py
from django.conf.urls import url

from picuploader import views

app_name = "picuploader"

urlpatterns = [
    url(r'upload/$', views.upload_picture, name="upload_picture"),
    url(r'^upload/success/$', views.show_picture_uploaded, name="picture_success"),
    url(r'^picture/(?P<pk>\d+)$', views.PictureDetailView.as_view(), name="picture_detail"),
    url(r'^picture/remove/(?P<pk>\d+)$', views.PictureDeleteView.as_view(), name="picture_remove"),
    url(r'$', views.show_pictures, name="show_pictures"),
]

picuploader/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import post_delete
from django.dispatch import receiver


class Picture(models.Model):
    name= models.CharField(max_length=500)
    picturefile= models.ImageField(upload_to='images/', null=True, verbose_name="")

    def __str__(self):
        return str(self.picturefile)

    def get_absolute_url(self):
        return reverse("picuploader:picture_detail", kwargs={"pk": self.pk})


@receiver(post_delete, sender=Picture)
def submission_delete(sender, instance, **kwargs):
    """
        Deletes the file relative to the picture object that is deleted.
    """
    instance.picturefile.delete(False)

picuploader/forms.py
from django import forms
from .models import Picture

class PictureForm(forms.ModelForm):
    class Meta:
        model= Picture
        fields= ["name", "picturefile"]

picuploader/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import (TemplateView, ListView, CreateView, UpdateView, DetailView, DeleteView)

from .models import Picture
from .forms import PictureForm


def upload_picture(request):

    form = PictureForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        form.save()

        return redirect('picuploader:picture_success')

    return render(request, 'picture_upload.html', {'form': form})


def show_picture_uploaded(request):
    lastpicture = Picture.objects.last()
    picture = lastpicture.picturefile

    context = {
        'picture': picture,
    }

    return render(request, 'success.html', context)


def show_pictures(request):
    pictures = Picture.objects.all()

    context = {
        'pictures': pictures
    }

    return render(request, 'pics.html', context)


class PictureDetailView(DetailView):
    model = Picture


class PictureDeleteView(DeleteView):
    model = Picture
    success_url = reverse_lazy("picuploader:show_pictures")

pic_upload/templates/base.html
<!DOCTYPE html>
{% load static i18n %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Zen Pictures!</title>

  <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Medium style Editor-->
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

  <!-- Custom Css -->
  <link rel="stylesheet" href="{% static 'pic_upload/css/styles.css' %}">

  <!-- google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">


</head>
<body>

  <!-- Navbar -->
  <nav class="navbar navbar-default techfont custom-navbar">
    <div class="container">
      <ul class="nav navbar-nav">
        <li><a class="navbar-brand bigbrand" href="{% url 'picuploader:show_pictures' %}">Zen Pictures</a></li>
        <li><a class="" href="{% url 'picuploader:upload_picture' %}">Upload Pictures</a></li>
        <li><a class="" href="#">About</a></li>
      </ul>
    </div>

  </nav>
  <!--Content block -->

  <div class="content container">
    <div class="row">
      <div class="col-md-8">
        <div class="blog_posts">
            {% block content %}
            {% endblock %}
        </div>
      </div>
    </div>

  </div>


</body>
</html>

picuploader/templates/pics.html
{% extends "base.html" %}
{% block content %}

  <div class="centerstage">
{#  {% for post in post_list %}#}
{#    <div class="post">#}
{#      <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>#}
{#      <div class="date">#}
{#        <p>Published on: {{ post.published|date:"D M Y" }}</p>#}
{#      </div>#}
{#    <a href="{% url 'blog:post_detail' pk=post.pk %}"> Comments: {{ post.approve_comments.count }}</a>#}
{##}
{#    </div>#}
{#  {% endfor %}#}
    <strong>Pictures!</strong>

    {% if not pictures %}
      <div><h3>Awwwwww! Empty here? <a class="" href="{% url 'picuploader:upload_picture' %}">Upload a picture!</a></h3></div>

    {% else %}
      <div>
      {% for picture in pictures %}

          <div class="col-md-4">

            <img src="{{ picture.picturefile.url }}" class="img-responsive" style="width: 100%; float: left; margin-right: 10px;" />
            {{ picture.name }}
            <a class="btn btn-primary" href="{% url 'picuploader:picture_remove' pk=picture.pk %}"> Delete Picture </a>
            <a class="btn btn-primary" href="{% url 'picuploader:picture_detail' pk=picture.pk %}"> Detail</a>
          </div>
      {% endfor %}
      </div>
    {% endif %}

  </div>
{% endblock %}

picuploader/templates/picture_upload.html
{% extends "base.html" %}
{% block content %}
  <div class="centerstage">
    <strong>Picture Upload</strong>

    <form enctype="multipart/form-data" method="POST" action="">
      {% csrf_token %}
      {{ form.as_p }}
    <input type="submit" value="Upload"/>
    </form>
  </div>
{% endblock %}

picuploader/templates/picuploader/picture_confirm_delete.html
{% extends "base.html" %}
{% block content %}

  <strong>Pictures Detail!</strong>
  <div class="centerstage">

     <form method="post">
      {% csrf_token %}
      <p>Are you sure to delete "{{ object }}"?</p>
      <input type="submit" class="btn btn-danger" value="Confirm">
     </form>

  </div>
{% endblock %}

picuploader/templates/picuploader/picture_detail.html
{% extends "base.html" %}
{% block content %}

  <strong>Pictures Detail!</strong>
  <div class="centerstage">
      <div class="col-md-3">
        {{ picture.name }}
        <img src="{{ picture.picturefile.url }}" />
      </div>
  </div>
{% endblock %}

picuploader/templates/success.html
{% extends "base.html" %}
{% block content %}
  <div class="centerstage">
    <strong>Picture Uploaded Successfully!</strong>
    <br><br>
    <img src='{{ picture.url }}' width="100">

  </div>
{% endblock %}